### ISSUE TITLE
ActionName from maec.vocabs.vocabs

### ISSUE THREAD

**Issue by abulhol** [MAECProject/python-maec#82]
Why does this work (using cybox.common.vocabs)
```
action = MalwareAction()
action.name = ActionName.TERM_SEND_DNS_QUERY
```
and this not? (using maec.vocabs.vocabs)
```
action = MalwareAction()
action.name = HTTPActionName.TERM_SEND_HTTP_GET_REQUEST
```
giving me following error:
```
Traceback (most recent call last):
  File "C:\Users\XXX\workspace\TestMAEC\testscript.py", line 110, in <module>
    action.name = HTTPActionName.TERM_SEND_HTTP_GET_REQUEST
  File "C:\Python27\lib\site-packages\cybox\__init__.py", line 659, in __set__
    processed = self._handle_value(value)
  File "C:\Python27\lib\site-packages\cybox\common\vocabs.py", line 54, in _handle_value
    return vocab(value)
  File "C:\Python27\lib\site-packages\cybox\common\vocabs.py", line 71, in __init__
    self.value = value
  File "C:\Python27\lib\site-packages\cybox\common\vocabs.py", line 90, in value
    raise ValueError(error)
ValueError: Value must be one of ('Close Registry Key', 'Get Elapsed System Up Time', 'Get System Time', [...] 'Set System Time'). Received 'send http get request'
```

**Comment by ikiril01** [comment]
Hi @abulhol, you'll need to wrap the value in `VocabString` instance from CybOX Common:

```python
from cybox.common import VocabString

action = MalwareAction()
action.name = VocabString(HTTPActionName.TERM_SEND_HTTP_GET_REQUEST)
```

This is primarily because MAEC has multiple vocabularies applicable to a particular field (Action/Name), whereas CybOX has one.

**Comment by abulhol** [comment]
Ok, most interesting. The world of MAEC is quite extensive and full of surprises. :-)

**Comment by ikiril01** [comment]
Extensive is good, but there are certainly things we could do better. Accordingly, we're trying to greatly simplify some of the core MAEC constructs for the next version, v5.0. For example, we're planning on having only one vocabulary for Action Names :-)

**Comment by abulhol** [comment]
Super Gut! :-)
