### ISSUE TITLE
UnicodeDecodeError installing 4.1.0.15

### ISSUE THREAD

**Issue by erickatwork** [MAECProject/python-maec#96]
Think this bug got reintroduced with v4.1.0.15. 

https://github.com/MAECProject/python-maec/issues/94

```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-t1okssb6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-t1okssb6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-t1okssb6/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-t1okssb6/setup.py", line 54, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-req-build-t1okssb6/setup.py", line 27, in get_long_description
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 141: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by emmanvg** [comment]
@ec4n6 thanks for opening the issue. The problem has been fixed in the new release.
